dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes
  ecmwf/eckit@develop
  ecmwf/metkit
  ecmwf/fdb
  ecmwf/gribjump
  ecmwf/conflator@main
dependency_cmake_options: |
  ecmwf/gribjump: "-DENABLE_FDB_BUILD_TOOLS=ON"
dependency_branch: develop
parallelism_factor: 8
self_build: false