# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index_tree.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10index_tree.proto\x12\nindex_tree"\x9a\x01\n\x04Node\x12\x0c\n\x04\x61xis\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\t\x12\x0f\n\x07indexes\x18\x03 \x03(\x03\x12\x0e\n\x06result\x18\x04 \x03(\x01\x12\x13\n\x0bsize_result\x18\x05 \x03(\x03\x12"\n\x08\x63hildren\x18\x06 \x03(\x0b\x32\x10.index_tree.Node\x12\x1b\n\x13size_indexes_branch\x18\x07 \x03(\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "index_tree_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NODE"]._serialized_start = 33
    _globals["_NODE"]._serialized_end = 187
# @@protoc_insertion_point(module_scope)
